sudo: required
services:
    - docker

before_install:
    - docker build -t tristanmueller/docker-react -f Dockerfile.dev .

script:
    - docker run tristanmueller/docker-react npm run test -- --coverage